// ProvisionalSanctionLetter.js
import React, { useRef } from "react";
import { Download, ChevronsRight, RefreshCcw } from "lucide-react";

// NOTE: For the download functionality to work, you must install and import
// a client-side PDF library like html2pdf.js, jspdf, or html2canvas.
// Example command (for html2pdf): npm install html2pdf.js

// Assuming a function like this is available globally or imported if using jspdf/html2canvas setup
const handleDownloadPlaceholder = (contentRef, filename) => {
  if (contentRef.current) {
    // --- Placeholder for actual PDF generation logic ---
    console.log("Starting PDF Download for:", filename);

    // This is where you would integrate html2pdf(contentRef.current).save(filename);
    // Since I cannot run external libraries, this alert simulates success.
    alert(
      `Successfully simulated download of '${filename}'! Please integrate a library like html2pdf.js.`
    );
    // ----------------------------------------------------
  }
};

const SanctionLetterContent = ({
  userData,
  loanDetails,
  onAcceptAndProceed,
}) => {
  const contentRef = useRef(null); // Ref for the content to be converted to PDF

  const handleDownloadPDF = () => {
    const filename = `Happirate_PSL_${userData.lastName}.pdf`;
    handleDownloadPlaceholder(contentRef, filename);
  };

  // Combine fetched user data and new loan request details
  const borrowerName = `${userData.firstName} ${userData.lastName}`;
  const requestedAmount = `₹ ${Number(loanDetails.loanAmount).toLocaleString(
    "en-IN"
  )}`;
  const requestedTenure = "5 Years (Placeholder)"; // Using a fixed placeholder as tenure wasn't captured

  // --- Static Data from your file ---
  const issuanceDate = "December 9, 2025";
  const referenceID = "HPR/PSL/120925/4532";
  const profileScore = "Excellent (CIBIL: 785)";
  const lowestAvailableRate = "10.20%";
  const preferredRate = "9.00%";

  const offers = [
    {
      rank: 1,
      lender: "IndusLand Bank - Premium Personal Loan",
      amount: "₹ 10,00,000",
      apr: "10.50%",
      tenure: "12 - 60 Months",
      fee: "1.0% of Loan Amount + GST",
      confidence: "95%",
    },
    {
      rank: 2,
      lender: "Swift Finance NBFC - Digital Express Loan",
      amount: "₹ 12,50,000",
      apr: "11.25%",
      tenure: "12 - 72 Months",
      fee: "Flat ₹ 5,000 + GST",
      confidence: "90%",
    },
    {
      rank: 3,
      lender: "StateCo Bank - Personal Loan",
      amount: "₹ 8,00,000",
      apr: "10.20%",
      tenure: "36 - 84 Months",
      fee: "1.5% of Loan Amount + GST",
      confidence: "80%",
    },
  ];

  const correctiveActions = [
    {
      gap: "Rate Gap (1.20% difference)",
      limitation:
        "Your current Debt-to-Income (DTI) ratio is at 45%, which increases perceived risk for the lowest interest tiers.",
      action:
        "Immediate Step: Reduce your high-interest debt exposure. Clearing the outstanding balance on Credit Card X (₹ 55,000) will immediately lower your DTI to 38%.",
    },
    {
      gap: "Score Optimization",
      limitation:
        "Your CIBIL score is excellent (785) but could be 'Exceptional' (800+) for the best rates.",
      action:
        "Long-Term Step: Ensure consistent utilization of less than 20% on all credit cards for the next three billing cycles. This will push your score into the highest tier, qualifying you for the sub-10% offers.",
    },
  ];

  return (
    <div className="bg-white p-6 rounded-lg shadow-lg max-h-[80vh] flex flex-col">
      <div className="flex justify-between items-center border-b pb-3 mb-4 sticky top-0 bg-white z-20">
        {" "}
        {/* Higher z-index for sticky header */}
        <h2 className="text-2xl font-extrabold text-blue-800">
          PROVISIONAL SANCTION LETTER
        </h2>
        <button
          onClick={handleDownloadPDF}
          className="flex items-center space-x-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition shadow-md"
        >
          <Download size={18} />
          <span>Download PSL</span>
        </button>
      </div>

      {/* Scrollable Content Area: Use ref here for PDF generation */}
      <div
        ref={contentRef}
        className="overflow-y-auto pr-2 flex-grow custom-scrollbar"
      >
        <p className="text-sm text-gray-500 mb-4">
          Generated by Happirate AI Smart Lending Engine
        </p>

        {/* General Details */}
        <div className="bg-blue-50 p-4 rounded-lg mb-6 shadow-inner">
          <h3 className="font-bold text-lg text-blue-700 mb-2">
            Application Snapshot
          </h3>
          <div className="grid grid-cols-2 gap-2 text-sm">
            <p>
              <strong>Date of Issuance:</strong> {issuanceDate}
            </p>
            <p>
              <strong>Reference ID:</strong> {referenceID}
            </p>
            <p className="col-span-2">
              <strong>Borrower Name:</strong> {borrowerName}
            </p>
            <p>
              <strong>Profile Score:</strong>{" "}
              <span className="text-green-600 font-semibold">
                {profileScore}
              </span>
            </p>
            <p>
              <strong>Requested Loan:</strong>{" "}
              {loanDetails.loanType.charAt(0).toUpperCase() +
                loanDetails.loanType.slice(1)}
            </p>
            <p className="col-span-2">
              <strong>Requested Amount & Tenure:</strong> {requestedAmount} for{" "}
              {requestedTenure}
            </p>
          </div>
        </div>

        {/* Section A: Eligible Offers */}
        <div className="mb-6">
          <h3 className="text-xl font-bold text-gray-800 border-b pb-1 mb-3">
            SECTION A: ELIGIBLE & SANCTIONED OFFERS
          </h3>
          <p className="text-sm text-gray-600 mb-3">
            Based on the assessment of your current credit profile and verified
            income, we identified the following top loan offers:
          </p>
          <div className="space-y-4">
            {offers.map((offer) => (
              <div
                key={offer.rank}
                className="p-4 border border-gray-200 rounded-lg shadow-sm hover:shadow-md transition duration-200"
              >
                <div className="flex justify-between items-center mb-2">
                  <h4 className="text-base font-bold text-purple-700">
                    Rank {offer.rank}: {offer.lender}
                  </h4>
                  <span
                    className={`text-sm font-semibold ${
                      offer.confidence.startsWith("9")
                        ? "text-green-600"
                        : "text-yellow-600"
                    }`}
                  >
                    Approval Confidence: {offer.confidence}
                  </span>
                </div>
                <div className="grid grid-cols-3 gap-y-1 text-sm text-gray-700">
                  <p>
                    <strong>Max Sanction:</strong>{" "}
                    <span className="font-semibold">{offer.amount}</span>
                  </p>
                  <p>
                    <strong>True APR:</strong>{" "}
                    <span className="font-semibold">{offer.apr}</span>
                  </p>
                  <p>
                    <strong>Tenure:</strong> {offer.tenure}
                  </p>
                  <p className="col-span-3">
                    <strong>Processing Fee:</strong> {offer.fee}
                  </p>
                </div>
              </div>
            ))}
          </div>
          <p className="text-xs text-gray-500 mt-3">
            *All offers are for the maximum amount you qualify for based on your
            income.
          </p>
        </div>

        {/* Section B: Corrective Action & Guidance */}
        <div className="mb-6">
          <h3 className="text-xl font-bold text-gray-800 border-b pb-1 mb-3">
            SECTION B: CORRECTIVE ACTION & GUIDANCE
          </h3>
          <p className="text-sm text-gray-600 mb-3">
            Your Requested Rate was **{preferredRate}**. The lowest available
            rate is **{lowestAvailableRate}**. To help you achieve your desired
            rate, our AI provides personalized action points:
          </p>
          <div className="space-y-4">
            {correctiveActions.map((action, index) => (
              <div
                key={index}
                className="p-4 bg-yellow-50 border-l-4 border-yellow-500 rounded-r-lg shadow-sm"
              >
                <h4 className="font-semibold text-orange-700 mb-1">
                  {action.gap}
                </h4>
                <p className="text-sm mb-2">
                  <span className="font-medium">Limitation:</span>{" "}
                  {action.limitation}
                </p>
                <p className="text-sm text-gray-800">
                  <span className="font-bold">Action:</span> {action.action}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Next Steps - Modified to use onAcceptAndProceed */}
        <div className="mt-8 pt-4 border-t border-gray-200">
          <h3 className="text-lg font-bold text-gray-800 mb-2">
            Your Next Step:
          </h3>
          <div className="flex justify-between space-x-4">
            <button
              onClick={onAcceptAndProceed}
              className="flex-1 flex items-center justify-center space-x-2 px-4 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition"
            >
              <ChevronsRight size={20} />
              <span>ACCEPT OFFER & PROCEED</span>
            </button>
            <button className="flex-1 flex items-center justify-center space-x-2 px-4 py-3 bg-gray-200 text-gray-800 rounded-lg font-semibold hover:bg-gray-300 transition">
              <RefreshCcw size={16} />
              <span>RE-ASSESS LATER (60 Days)</span>
            </button>
          </div>
        </div>

        {/* Disclaimer */}
        <div className="mt-6 text-xs text-gray-500 border-t pt-4">
          <p>
            <strong>Disclaimer:</strong> This is a provisional sanction letter
            generated by Happirate's AI and is not a guarantee of final loan
            disbursement. Final approval is subject to the chosen lender's
            successful completion of due diligence, documentation verification,
            and mandatory KYC checks. Happirate is a facilitator and is not the
            lending entity.
          </p>
          <p className="mt-1">
            Offer Validity: This provisional sanction is valid for 7 calendar
            days from the Date of Issuance ({issuanceDate}).
          </p>
        </div>
      </div>
    </div>
  );
};

export default SanctionLetterContent;
